// [v1.4.0] 브라우저 localStorage 복원 유틸리티입니다.
// 저장 key와 마이그레이션 기본값을 React 컴포넌트 밖에 고정합니다.

import type { ChatPreset, ChatSession } from '../types';
import {
  COMPRESSION_RATIO_STORAGE_KEY,
  DEFAULT_COMPRESSION_RATIO,
  MODEL_OVERRIDES_STORAGE_KEY,
  PRESETS_STORAGE_KEY,
  SESSION_STORAGE_KEY
} from '../constants';
import {
  clampNumber,
  normalizeGenerationSettings,
  type ModelOverrideMap
} from './modelMetadata';

export function readStoredCompressionRatio(): number {
  const stored = localStorage.getItem(COMPRESSION_RATIO_STORAGE_KEY);
  if (!stored) return DEFAULT_COMPRESSION_RATIO;
  const parsed = Number(stored);
  return clampNumber(parsed, 0.1, 1);
}

export function normalizeSession(raw: ChatSession, compressionRatio: number): ChatSession {
  return {
    ...raw,
    isTitleAutoGenerated: raw.isTitleAutoGenerated ?? false,
    generationSettings: normalizeGenerationSettings(raw.generationSettings),
    compressionRatio: clampNumber(raw.compressionRatio ?? compressionRatio, 0.1, 1),
    contextSummary: raw.contextSummary ?? '',
    summarizedMessageIds: raw.summarizedMessageIds ?? [],
    messages: (raw.messages ?? []).map(message => ({
      ...message,
      status: message.status ?? 'complete'
    }))
  };
}

export function readStoredModelOverrides(): ModelOverrideMap {
  const stored = localStorage.getItem(MODEL_OVERRIDES_STORAGE_KEY);
  if (!stored) return {};
  try {
    return JSON.parse(stored) as ModelOverrideMap;
  } catch (e) {
    console.error('모델 메타데이터 보정값 복구 에러:', e);
    return {};
  }
}

export function readStoredPresets(): ChatPreset[] {
  const stored = localStorage.getItem(PRESETS_STORAGE_KEY);
  if (!stored) return [];
  try {
    const parsed = JSON.parse(stored) as ChatPreset[];
    return parsed.map(preset => ({
      ...preset,
      generationSettings: normalizeGenerationSettings(preset.generationSettings),
      compressionRatio: clampNumber(preset.compressionRatio ?? DEFAULT_COMPRESSION_RATIO, 0.1, 1)
    }));
  } catch (e) {
    console.error('프리셋 복구 에러:', e);
    return [];
  }
}

export function readStoredSessions(): ChatSession[] {
  const stored = localStorage.getItem(SESSION_STORAGE_KEY);
  if (!stored) return [];

  try {
    const compressionRatio = readStoredCompressionRatio();
    return (JSON.parse(stored) as ChatSession[]).map(session => normalizeSession(session, compressionRatio));
  } catch (e) {
    console.error('세션 복구 에러:', e);
    return [];
  }
}
