// [v1.4.0] 개정 반영
// - [v1.0.0] 최초 작성: 3대 프로바이더 및 대화방 타입 체계 정의.
// - [v1.1.0] 2차 개정: 5대 프로바이더(LM Studio, Local LLM) 타입 추가, Super Prompt 모델 규격 및 세션 바인딩 옵션 확장 완료.
// - [v1.4.0] 3차 개정: 스트리밍 메시지 상태, 백업 번들, Inspector, 채팅 프리셋 타입 추가.

// ProviderType은 지원하는 5개 API 프로바이더의 물리 식별자 타입입니다.
export type ProviderType = 'openrouter' | 'opencode_zen' | 'opencode_go' | 'lm_studio' | 'local_llm';

// ProviderState는 프로바이더의 연동 정보 요약을 클라이언트에 저장하는 규격입니다.
export interface ProviderState {
  name: ProviderType;
  displayName: string;
  hasKey: boolean;
  baseUrl: string;
  configStatus: 'missing' | 'ready' | 'invalid_key';
  statusMessage: string;
}

// ModelInfo는 각 프로바이더 API로부터 인출한 AI 모델의 메타데이터 규격입니다.
export interface ModelInfo {
  id: string;
  name: string;
  contextLength: number;
  maxInputTokens: number;
  maxOutputTokens: number;
  supportedParameters: string[];
  supportsVision: boolean;
  supportsTemperature: boolean;
  supportsTopP: boolean;
  supportsTopK: boolean;
  supportsRepetitionPenalty: boolean;
  metadataSource: 'openrouter' | 'lm_studio_api_v0' | 'openai_compatible' | 'manual' | 'unknown';
  isContextEstimated: boolean;
}

// ModelMetadataOverride는 모델 API가 한도 정보를 주지 않을 때 사용자가 직접 저장하는 보정값입니다.
export interface ModelMetadataOverride {
  contextLength: number;
  maxInputTokens: number;
  maxOutputTokens: number;
}

// GenerationSettings는 모델이 지원하는 경우에만 원격 payload에 포함되는 생성 파라미터 집합입니다.
export interface GenerationSettings {
  temperature: number;
  topP: number;
  topK: number;
  repetitionPenalty: number;
}

// SummaryCompressionResponse는 백엔드 요약 프록시가 반환하는 컨텍스트 압축 결과입니다.
export interface SummaryCompressionResponse {
  summary: string;
  summarized_message_ids: string[];
}

// StreamProxyEvent는 백엔드 SSE가 브라우저로 전달하는 내부 스트림 이벤트입니다.
export interface StreamProxyEvent {
  type: 'delta' | 'done' | 'error';
  content?: string;
}

// SuperPrompt는 사용자가 등록한 시스템 프롬프트(페르소나 지침) 데이터 구조입니다.
export interface SuperPrompt {
  name: string;
  content: string;
}

// AttachmentInfo는 메시지에 첨부된 이미지 또는 파일의 구조입니다.
export interface AttachmentInfo {
  name: string;
  type: string;
  size: number;
  url: string; // Base64 인코딩
}

// OpenAIContentPart는 텍스트와 이미지 첨부를 함께 보낼 때 사용하는 OpenAI 호환 메시지 조각입니다.
export type OpenAIContentPart =
  | { type: 'text'; text: string }
  | { type: 'image_url'; image_url: { url: string } };

// OpenAIMessagePayload는 백엔드 프록시로 넘기는 메시지 페이로드의 최소 호환 규격입니다.
export interface OpenAIMessagePayload {
  role: ChatMessage['role'];
  content: string | OpenAIContentPart[];
}

// ChatCompletionResponse는 OpenAI 호환 응답에서 현재 UI가 소비하는 최소 필드입니다.
export interface ChatCompletionResponse {
  choices?: {
    message?: {
      content?: string;
    };
  }[];
}

// ChatMessage는 단일 말풍선 대화 메시지의 구조입니다.
export interface ChatMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: string;
  attachments?: AttachmentInfo[];
  status?: 'complete' | 'streaming' | 'cancelled' | 'error';
  errorMessage?: string;
}

// ChatSession은 개별 대화방(세션)의 정보 홀더입니다.
export interface ChatSession {
  id: string;
  title: string;
  isTitleAutoGenerated?: boolean;
  messages: ChatMessage[];
  provider: ProviderType;
  model: string;
  activeSystemPromptName?: string; // 대화방에서 가동 중인 Super Prompt 지침의 이름
  generationSettings?: GenerationSettings;
  compressionRatio?: number;
  contextSummary?: string;
  summarizedMessageIds?: string[];
}

// ChatPreset은 API Key와 Base URL을 제외한 대화 실행 설정 묶음입니다.
export interface ChatPreset {
  id: string;
  name: string;
  provider: ProviderType;
  model: string;
  activeSystemPromptName?: string;
  generationSettings: GenerationSettings;
  compressionRatio: number;
  modelOverride?: ModelMetadataOverride;
  createdAt: string;
  updatedAt: string;
}

// ChatExportBundle은 복원용 JSON 백업 파일의 최상위 스키마입니다.
export interface ChatExportBundle {
  schemaVersion: 'liteflashchat.v1.4.0';
  exportedAt: string;
  sessions: ChatSession[];
  modelOverrides: Record<string, ModelMetadataOverride>;
  presets: ChatPreset[];
}

// InspectorSnapshot은 마지막 요청/응답의 안전한 디버깅 스냅샷입니다.
export interface InspectorSnapshot {
  id: string;
  timestamp: string;
  provider: ProviderType;
  model: string;
  endpoint: '/api/chat' | '/api/chat/stream' | '/api/chat/summary';
  streaming: boolean;
  sanitizedRequest: Record<string, unknown>;
  responseStatus?: number;
  responsePreview?: string;
  errorMessage?: string;
  usedContextSummary: boolean;
}
